apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jhipster-registry
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: jhipster-registry
    spec:
      containers:
      - name: jhipster-registry
        image: jhipster/jhipster-registry:v4.1.1
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "-ec", "sleep 3000"]
        volumeMounts:
        - mountPath: "./central-server-config"
          name: central-config
        env:
        - name: _JAVA_OPTIONS
          value: -Xmx256m -Xms256m
        - name: SPRING_PROFILES_ACTIVE
          value: dev,swagger,uaa
        - name: SPRING_SECURITY_USER_PASSWORD
          value: admin
        - name: JHIPSTER_REGISTRY_PASSWORD
          value: admin
        - name: SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_TYPE
          value: native
        - name: SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_SEARCH_LOCATIONS
          value: file:./central-config/localhost-config/
        ports:
        - containerPort: 8761
      volumes:
      - name: central-config
        persistentVolumeClaim:
          claimName: central-config-pvc
